### PR TITLE
pull wallet and wallet id

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #19.

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job [#27](https://github.com/amihaiemil/zold-java-client/issues/27) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:amihaiemil/zold-java-client#27` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#27](https://github.com/amihaiemil/zold-java-client/issues/27) is now out of scope

**Pull request merged**
