### PR TITLE
Added utilities

### PR DESCRIPTION
**Pull request by amihaiemil**
For #15. Added response handlers, matchers and classes for unit testing.

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job [#24](https://github.com/amihaiemil/zold-java-client/issues/24) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:amihaiemil/zold-java-client#24` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#24](https://github.com/amihaiemil/zold-java-client/issues/24) is now out of scope

**Pull request merged**
