### PR TITLE
Next methods were implemented: pull(), waitForJob(), walletId()

### PR DESCRIPTION
**Pull request by OleksandrSankin**
I didn't manage strictly follow to ruby API because:
- method wait() already exists in each object in Java - renamed to waitForJob() 
- method id() check-style didn't accept - renamed to walletId()

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#17](https://github.com/amihaiemil/zold-java-client/issues/17) is assigned to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/4652f4be-73c2-42b2-9959-49e1c3eaabac); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by ammaratef45** [comment]
@amihaiemil should we accept PRs to be such big? as I understand they must be small as we are following PDD principle right?

**Comment by amihaiemil** [comment]
@OleksandrSankin This PR is too big, I'm sorry... 

1. It changes too many things which are not related to each other
2. it doesn't respect the architecture I have in mind. First of all, I think we should do the waiting for the user (so no ``wait()`` methods exposed to the user at all: they shouldn't have to care about network details. 

However, don't delete your branch, maybe you can make smaller PRS with more focused changes later (but open Issues first, and discuss them beforehand).

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#17](https://github.com/amihaiemil/zold-java-client/issues/17) is now out of scope

**Comment by 0crat** [comment]
Job `gh:amihaiemil/zold-java-client#17` doesn't exist in WBS, can't create order

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request closed without merging**
