### PR TITLE
ZoldNet skeleton

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #4

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#6](https://github.com/amihaiemil/zold-java-client/issues/6) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job `gh:amihaiemil/zold-java-client#6` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#6](https://github.com/amihaiemil/zold-java-client/issues/6) is now out of scope

**Comment by 0crat** [comment]
Job `gh:amihaiemil/zold-java-client#6` doesn't exist in WBS, can't create order

**Pull request merged**
