### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by amihaiemil**
more fixes

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#22](https://github.com/amihaiemil/zold-java-client/issues/22) is now in scope, role is `REV`

**Comment by ammaratef45** [comment]
@amihaiemil 
I will take care of things like this better next time 😉 
Thanks for having my back 😆

**Comment by 0crat** [comment]
Job `gh:amihaiemil/zold-java-client#22` is not assigned, can't get performer

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#22](https://github.com/amihaiemil/zold-java-client/issues/22), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#22](https://github.com/amihaiemil/zold-java-client/issues/22) is now out of scope

**Comment by 0crat** [comment]
The job [#22](https://github.com/amihaiemil/zold-java-client/issues/22) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/9894d881-cc0a-42b5-a2c5-c35454d2e6d7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Pull request merged**
