### PR TITLE
#56: balance and find wallet operations covered with tests.

### PR DESCRIPTION
**Pull request by denis-konovalyenko**
This is a partial solution for issue #56.
Wallet balance and find operations have been covered with the unit tests.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#57](https://github.com/amihaiemil/zold-java-client/issues/57) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job [#57](https://github.com/amihaiemil/zold-java-client/issues/57) is already in scope

**Comment by 0crat** [comment]
This pull request [#57](https://github.com/amihaiemil/zold-java-client/issues/57) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/GFCHY7NQG/2bc7f224-87a0-4cb7-8dd5-8912730a3ceb); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by denis-konovalyenko** [comment]
@g4s8 , could you please take a look?

**Comment by denis-konovalyenko** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/amihaiemil/zold-java-client/issues/57#issuecomment-478940642))

@denis-konovalyenko This is what I know about this job in GFCHY7NQG, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#57](https://github.com/amihaiemil/zold-java-client/issues/57) is [in scope](http://www.zerocracy.com/policy.html#14) for 7days
  * The role is `REV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [7days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/GFCHY7NQG?q=%7Bjob%3A%27gh%3Aamihaiemil%2Fzold-java-client%2357%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by denis-konovalyenko** [comment]
@ammaratef45 , @amihaiemil , is it possible that @g4s8 has resigned? I do not see this nick available in the list of participants to tag. If this is the case, could someone of you take a quick look at this pull request changes? Thanks!

**Comment by ammaratef45** [comment]
@rultor merge it.

**Comment by ammaratef45** [comment]
@denis-konovalyenko The method find have been changed in #58 ,
Please edit the test.

**Comment by denis-konovalyenko** [comment]
@ammaratef45 , the pull request has been updated to reflect issue #58 changes.

**Comment by ammaratef45** [comment]
@denis-konovalyenko Thanks

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@ammaratef45 FYI: rultor has a bug, it always tries to decrypt the files mentioned in ``.rultor.yml`` even when they are not required (they are not required for merging). On top of that, communication with the gpg server sometimes fails so that's why sometimes the error above happens. 

When it happens, just try to merge again and it should work.

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by ammaratef45** [comment]
@amihaiemil Yes, I remember that you've submitted this bug before, I saw it in rultor repository.

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31):

**Comment by 0crat** [comment]
The job [#57](https://github.com/amihaiemil/zold-java-client/issues/57) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
